# Generated by Django 6.0.7 on 2026-07-16 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=512)),
                ('kind', models.CharField(default='module', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DependencyEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(default='import', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='analysis.dependencynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='analysis.dependencynode')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=64)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('signature', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='projects.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'kind', 'name'], name='analysis_sy_project_f3cb71_idx')],
            },
        ),
    ]
