# Generated by Django 6.0.7 on 2026-07-16 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('detecting', 'Detecting languages'), ('analyzing', 'Static analysis'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexed', 'Indexed'), ('generating', 'Generating architecture'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('progress', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
            ],
        ),
    ]
